### ISSUE TITLE
Unexpected error when extracting for got

### ISSUE THREAD

**Issue by jasonkuhrt** [tydoc/extractor#60]
First found in https://github.com/tydoc/extractor/pull/59

When run against [`got`](https://github.com/sindresorhus/got)

```
❯ DEBUG='*' tydoc project source/index --ignore-diagnostics
  @oclif/config reading core plugin /Users/jasonkuhrt/projects/tydoc/extractor +0ms
  @oclif/config loadJSON /Users/jasonkuhrt/projects/tydoc/extractor/package.json +0ms
  @oclif/config loadJSON /Users/jasonkuhrt/projects/tydoc/extractor/oclif.manifest.json +1ms
  @oclif/config:tydoc using manifest from /Users/jasonkuhrt/projects/tydoc/extractor/oclif.manifest.json +0ms
  @oclif/config reading user plugins pjson /Users/jasonkuhrt/.local/share/tydoc/package.json +0ms
  @oclif/config loadJSON /Users/jasonkuhrt/.local/share/tydoc/package.json +1ms
  @oclif/config loading plugins [ '@oclif/plugin-help' ] +1ms
  @oclif/config reading core plugin /Users/jasonkuhrt/projects/tydoc/extractor/node_modules/@oclif/plugin-help +0ms
  @oclif/config loadJSON /Users/jasonkuhrt/projects/tydoc/extractor/node_modules/@oclif/plugin-help/package.json +2ms
  @oclif/config loadJSON /Users/jasonkuhrt/projects/tydoc/extractor/node_modules/@oclif/plugin-help/oclif.manifest.json +0ms
  @oclif/config:@oclif/plugin-help using manifest from /Users/jasonkuhrt/projects/tydoc/extractor/node_modules/@oclif/plugin-help/oclif.manifest.json +0ms
  @oclif/config config done +2ms
  @oclif/config start init hook +0ms
  @oclif/config init hook done +0ms
  tydoc init version: @oclif/command@1.8.0 argv: [ 'project', 'source/index', '--ignore-diagnostics' ] +0ms
  @oclif/config runCommand project [ 'source/index', '--ignore-diagnostics' ] +2ms
  @oclif/config registering ts-node at /Users/jasonkuhrt/projects/tydoc/extractor +0ms
  @oclif/config:tydoc require /Users/jasonkuhrt/projects/tydoc/extractor/src/cli/commands/project.ts +137ms
  @oclif/config start prerun hook +630ms
  @oclif/config prerun hook done +0ms
  tydoc:project init version: @oclif/command@1.8.0 argv: [ 'source/index', '--ignore-diagnostics' ] +0ms
  tydoc:extract prjDir set to /Users/jasonkuhrt/find-tydoc-thing/got -- taken from passed config  +0ms
  tydoc:extract srcDir set to /Users/jasonkuhrt/find-tydoc-thing/got +843ms
  tydoc:extract outDir set to /Users/jasonkuhrt/find-tydoc-thing/got/dist +0ms
  tydoc:extract packageMainEntrypoint is /Users/jasonkuhrt/find-tydoc-thing/got/dist/source +1ms
  tydoc:extract mainModuleFilePathAbs is /Users/jasonkuhrt/find-tydoc-thing/got/source +0ms
  tydoc:extract found project source files  [
  '/Users/jasonkuhrt/find-tydoc-thing/got/source/create.ts',
  '/Users/jasonkuhrt/find-tydoc-thing/got/source/index.ts',
  '/Users/jasonkuhrt/find-tydoc-thing/got/source/types.ts',
  '/Users/jasonkuhrt/find-tydoc-thing/got/test/agent.ts',
  '/Users/jasonkuhrt/find-tydoc-thing/got/test/arguments.ts',
  '/Users/jasonkuhrt/find-tydoc-thing/got/test/cache.ts',
  '/Users/jasonkuhrt/find-tydoc-thing/got/test/cancel.ts',
  '/Users/jasonkuhrt/find-tydoc-thing/got/test/cookies.ts',
  '/Users/jasonkuhrt/find-tydoc-thing/got/test/create.ts',
  '/Users/jasonkuhrt/find-tydoc-thing/got/test/error.ts',
  '/Users/jasonkuhrt/find-tydoc-thing/got/test/gzip.ts',
  '/Users/jasonkuhrt/find-tydoc-thing/got/test/headers.ts',
  '/Users/jasonkuhrt/find-tydoc-thing/got/test/helpers.ts',
  '/Users/jasonkuhrt/find-tydoc-thing/got/test/hooks.ts',
  '/Users/jasonkuhrt/find-tydoc-thing/got/test/http.ts',
  '/Users/jasonkuhrt/find-tydoc-thing/got/test/https.ts',
  '/Users/jasonkuhrt/find-tydoc-thing/got/test/merge-instances.ts',
  '/Users/jasonkuhrt/find-tydoc-thing/got/test/normalize-arguments.ts',
  '/Users/jasonkuhrt/find-tydoc-thing/got/test/pagination.ts',
  '/Users/jasonkuhrt/find-tydoc-thing/got/test/post.ts',
  '/Users/jasonkuhrt/find-tydoc-thing/got/test/progress.ts',
  '/Users/jasonkuhrt/find-tydoc-thing/got/test/promise.ts',
  '/Users/jasonkuhrt/find-tydoc-thing/got/test/redirects.ts',
  '/Users/jasonkuhrt/find-tydoc-thing/got/test/response-parse.ts',
  '/Users/jasonkuhrt/find-tydoc-thing/got/test/retry.ts',
  '/Users/jasonkuhrt/find-tydoc-thing/got/test/stream.ts',
  '/Users/jasonkuhrt/find-tydoc-thing/got/test/timeout.ts',
  '/Users/jasonkuhrt/find-tydoc-thing/got/test/unix-socket.ts',
  '/Users/jasonkuhrt/find-tydoc-thing/got/test/url-to-options.ts',
  '/Users/jasonkuhrt/find-tydoc-thing/got/test/weakable-map.ts',
  '/Users/jasonkuhrt/find-tydoc-thing/got/benchmark/index.ts',
  '/Users/jasonkuhrt/find-tydoc-thing/got/benchmark/server.ts',
  '/Users/jasonkuhrt/find-tydoc-thing/got/source/as-promise/create-rejection.ts',
  '/Users/jasonkuhrt/find-tydoc-thing/got/source/as-promise/index.ts',
  '/Users/jasonkuhrt/find-tydoc-thing/got/source/as-promise/normalize-arguments.ts',
  '/Users/jasonkuhrt/find-tydoc-thing/got/source/as-promise/parse-body.ts',
  '/Users/jasonkuhrt/find-tydoc-thing/got/source/as-promise/types.ts',
  '/Users/jasonkuhrt/find-tydoc-thing/got/source/core/calculate-retry-delay.ts',
  '/Users/jasonkuhrt/find-tydoc-thing/got/source/core/index.ts',
  '/Users/jasonkuhrt/find-tydoc-thing/got/source/utils/deep-freeze.ts',
  '/Users/jasonkuhrt/find-tydoc-thing/got/source/utils/deprecation-warning.ts',
  '/Users/jasonkuhrt/find-tydoc-thing/got/test/helpers/create-http-test-server.ts',
  '/Users/jasonkuhrt/find-tydoc-thing/got/test/helpers/create-https-test-server.ts',
  '/Users/jasonkuhrt/find-tydoc-thing/got/test/helpers/slow-data-stream.ts',
  '/Users/jasonkuhrt/find-tydoc-thing/got/test/helpers/types.ts',
  '/Users/jasonkuhrt/find-tydoc-thing/got/test/helpers/with-server.ts',
  '/Users/jasonkuhrt/find-tydoc-thing/got/source/core/utils/dns-ip-version.ts',
  '/Users/jasonkuhrt/find-tydoc-thing/got/source/core/utils/get-body-size.ts',
  '/Users/jasonkuhrt/find-tydoc-thing/got/source/core/utils/get-buffer.ts',
  '/Users/jasonkuhrt/find-tydoc-thing/got/source/core/utils/is-form-data.ts',
  '/Users/jasonkuhrt/find-tydoc-thing/got/source/core/utils/is-response-ok.ts',
  '/Users/jasonkuhrt/find-tydoc-thing/got/source/core/utils/options-to-url.ts',
  '/Users/jasonkuhrt/find-tydoc-thing/got/source/core/utils/proxy-events.ts',
  '/Users/jasonkuhrt/find-tydoc-thing/got/source/core/utils/timed-out.ts',
  '/Users/jasonkuhrt/find-tydoc-thing/got/source/core/utils/unhandle.ts',
  '/Users/jasonkuhrt/find-tydoc-thing/got/source/core/utils/url-to-options.ts',
  '/Users/jasonkuhrt/find-tydoc-thing/got/source/core/utils/weakable-map.ts',
  '/Users/jasonkuhrt/find-tydoc-thing/got/test/types/create-test-server/index.d.ts',
  '/Users/jasonkuhrt/find-tydoc-thing/got/test/types/slow-stream/index.d.ts'
] +1ms
  tydoc:extract considering given entrypoint relative to srcDir: source/index +0ms
  tydoc:extract entrypointModulePathAbs is /Users/jasonkuhrt/find-tydoc-thing/got/source/index +1ms
  tydoc:extract no user settings to read from package.json +0ms
  tydoc:extract:export start +0ms
  tydoc:extract:export -> node kind is VariableDeclaration +0ms
  tydoc:extract:export -> type text is "import(\"/Users/jasonkuhrt/find-tydoc-thing/got/source/types\").Got" +3ms
  tydoc:extract:visible start +0ms
  tydoc:extract:visible -> type text is "import(\"/Users/jasonkuhrt/find-tydoc-thing/got/source/types\").Got" +1ms
  tydoc:extract:visible -> type location is app +2ms
  tydoc:extract:visible -> type is indexable +1ms
  tydoc:extract:visible -> type is callable +3ms
  tydoc:doc provisioning entry in type index: (source/types).Got +0ms
  tydoc:extract:visible handle property: PropertySignature stream import("/Users/jasonkuhrt/find-tydoc-thing/got/source/types").GotStream +2ms
  tydoc:extract:visible start +0ms
  tydoc:extract:visible -> type text is "import(\"/Users/jasonkuhrt/find-tydoc-thing/got/source/types\").GotStream" +1ms
  tydoc:extract:visible -> type location is app +4ms
  tydoc:extract:visible -> type is indexable +0ms
  tydoc:extract:visible -> type is callable +2ms
  tydoc:doc provisioning entry in type index: (source/types).GotStream +8ms
TypeError: Cannot read property 'getName' of undefined
    at /Users/jasonkuhrt/projects/tydoc/extractor/src/api/extractor/extract.ts:510:24
    at Array.map (<anonymous>)
    at propertyDocsFromType (/Users/jasonkuhrt/projects/tydoc/extractor/src/api/extractor/extract.ts:509:27)
    at /Users/jasonkuhrt/projects/tydoc/extractor/src/api/extractor/extract.ts:399:18
    at Manager.indexTypeIfApplicable (/Users/jasonkuhrt/projects/tydoc/extractor/src/api/extractor/doc.ts:89:24)
    at fromType (/Users/jasonkuhrt/projects/tydoc/extractor/src/api/extractor/extract.ts:394:20)
    at /Users/jasonkuhrt/projects/tydoc/extractor/src/api/extractor/extract.ts:519:13
    at Array.map (<anonymous>)
    at propertyDocsFromType (/Users/jasonkuhrt/projects/tydoc/extractor/src/api/extractor/extract.ts:509:27)
    at /Users/jasonkuhrt/projects/tydoc/extractor/src/api/extractor/extract.ts:399:18
```

**Comment by jasonkuhrt** [comment]
Progress in a79a9b9f8f5a6c09db528b44e20187e29c23319e

Now infinite loop like #77

**Comment by jasonkuhrt** [comment]
In profess in #89 

Now:

```
tydoc:package prjDir set to /Users/jasonkuhrt/projects/tydoc/tydoc/got -- taken from passed config  +0ms
  tydoc:package packageMain is /Users/jasonkuhrt/projects/tydoc/tydoc/got/dist/source +1ms
  tydoc:package sourceDir set to /Users/jasonkuhrt/projects/tydoc/tydoc/got +884ms
  tydoc:package outDir set to /Users/jasonkuhrt/projects/tydoc/tydoc/got/dist +0ms
  tydoc:package sourceMainModulePath is /Users/jasonkuhrt/projects/tydoc/tydoc/got/source +0ms
  tydoc:package no user settings to read from package.json +0ms
  tydoc:package layout calculated: {
  projectDir: '/Users/jasonkuhrt/projects/tydoc/tydoc/got',
  sourceDir: '/Users/jasonkuhrt/projects/tydoc/tydoc/got',
  sourceMainModulePath: '/Users/jasonkuhrt/projects/tydoc/tydoc/got/source',
  tydocSettingsInPackage: {},
  tsconfigPath: '/Users/jasonkuhrt/projects/tydoc/tydoc/got/tsconfig.json',
  packageJson: {
    name: 'got',
    version: '11.8.0',
    description: 'Human-friendly and powerful HTTP request library for Node.js',
    license: 'MIT',
    repository: 'sindresorhus/got',
    funding: 'https://github.com/sindresorhus/got?sponsor=1',
    main: 'dist/source',
    engines: { node: '>=10.19.0' },
    scripts: {
      test: 'xo && npm run build && nyc ava',
      release: 'np',
      build: 'del-cli dist && tsc',
      prepare: 'npm run build'
    },
    files: [ 'dist/source' ],
    keywords: [
      'http',       'https',
      'http2',      'get',
      'got',        'url',
      'uri',        'request',
      'simple',     'curl',
      'wget',       'fetch',
      'net',        'network',
      'gzip',       'brotli',
      'requests',   'human-friendly',
      'axios',      'superagent',
      'node-fetch', 'ky'
    ],
    dependencies: {
      '@sindresorhus/is': '^4.0.0',
      '@szmarczak/http-timer': '^4.0.5',
      '@types/cacheable-request': '^6.0.1',
      '@types/responselike': '^1.0.0',
      'cacheable-lookup': '^5.0.3',
      'cacheable-request': '^7.0.1',
      'decompress-response': '^6.0.0',
      'http2-wrapper': '^1.0.0-beta.5.2',
      'lowercase-keys': '^2.0.0',
      'p-cancelable': '^2.0.0',
      responselike: '^2.0.0'
    },
    devDependencies: {
      '@ava/typescript': '^1.1.1',
      '@sindresorhus/tsconfig': '^0.8.0',
      '@sinonjs/fake-timers': '^6.0.1',
      '@types/benchmark': '^2.1.0',
      '@types/express': '^4.17.9',
      '@types/node': '^14.14.9',
      '@types/node-fetch': '^2.5.7',
      '@types/pem': '^1.9.5',
      '@types/pify': '^3.0.2',
      '@types/request': '^2.48.5',
      '@types/sinon': '^9.0.8',
      '@types/tough-cookie': '^4.0.0',
      ava: '^3.13.0',
      axios: '^0.21.0',
      benchmark: '^2.1.4',
      'create-test-server': '^3.0.1',
      'del-cli': '^3.0.1',
      delay: '^4.4.0',
      express: '^4.17.1',
      'form-data': '^3.0.0',
      'get-stream': '^6.0.0',
      nock: '^13.0.5',
      'node-fetch': '^2.6.1',
      np: '^7.0.0',
      nyc: '^15.1.0',
      'p-event': '^4.2.0',
      pem: '^1.14.4',
      pify: '^5.0.0',
      sinon: '^9.2.1',
      'slow-stream': '0.0.4',
      tempy: '^1.0.0',
      'to-readable-stream': '^2.1.0',
      'tough-cookie': '^4.0.0',
      typescript: '4.1.2',
      xo: '^0.35.0'
    },
    types: 'dist/source',
    sideEffects: false,
    ava: { files: [Array], timeout: '1m', typescript: [Object] },
    nyc: { reporter: [Array], extension: [Array], exclude: [Array] },
    xo: { ignores: [Array], rules: [Object] },
    runkitExampleFilename: './documentation/examples/runkit-example.js'
  },
  tsMorphPoject: <ref *1> Project {
    _context: ProjectContext {
      logger: [ConsoleLogger],
      manipulationSettings: [ManipulationSettingsContainer],
      _project: [Circular *1],
      fileSystemWrapper: [TransactionalFileSystem],
      _compilerOptions: [CompilerOptionsContainer],
      compilerFactory: [CompilerFactory],
      inProjectCoordinator: [InProjectCoordinator],
      structurePrinterFactory: [StructurePrinterFactory],
      lazyReferenceCoordinator: [LazyReferenceCoordinator],
      directoryCoordinator: [DirectoryCoordinator],
      _languageService: [LanguageService]
    }
  }
} +0ms
  tydoc:extract found project source files: [
  '/Users/jasonkuhrt/projects/tydoc/tydoc/got/source/create.ts',
  '/Users/jasonkuhrt/projects/tydoc/tydoc/got/source/index.ts',
  '/Users/jasonkuhrt/projects/tydoc/tydoc/got/source/types.ts',
  '/Users/jasonkuhrt/projects/tydoc/tydoc/got/test/agent.ts',
  '/Users/jasonkuhrt/projects/tydoc/tydoc/got/test/arguments.ts',
  '/Users/jasonkuhrt/projects/tydoc/tydoc/got/test/cache.ts',
  '/Users/jasonkuhrt/projects/tydoc/tydoc/got/test/cancel.ts',
  '/Users/jasonkuhrt/projects/tydoc/tydoc/got/test/cookies.ts',
  '/Users/jasonkuhrt/projects/tydoc/tydoc/got/test/create.ts',
  '/Users/jasonkuhrt/projects/tydoc/tydoc/got/test/error.ts',
  '/Users/jasonkuhrt/projects/tydoc/tydoc/got/test/gzip.ts',
  '/Users/jasonkuhrt/projects/tydoc/tydoc/got/test/headers.ts',
  '/Users/jasonkuhrt/projects/tydoc/tydoc/got/test/helpers.ts',
  '/Users/jasonkuhrt/projects/tydoc/tydoc/got/test/hooks.ts',
  '/Users/jasonkuhrt/projects/tydoc/tydoc/got/test/http.ts',
  '/Users/jasonkuhrt/projects/tydoc/tydoc/got/test/https.ts',
  '/Users/jasonkuhrt/projects/tydoc/tydoc/got/test/merge-instances.ts',
  '/Users/jasonkuhrt/projects/tydoc/tydoc/got/test/normalize-arguments.ts',
  '/Users/jasonkuhrt/projects/tydoc/tydoc/got/test/pagination.ts',
  '/Users/jasonkuhrt/projects/tydoc/tydoc/got/test/post.ts',
  '/Users/jasonkuhrt/projects/tydoc/tydoc/got/test/progress.ts',
  '/Users/jasonkuhrt/projects/tydoc/tydoc/got/test/promise.ts',
  '/Users/jasonkuhrt/projects/tydoc/tydoc/got/test/redirects.ts',
  '/Users/jasonkuhrt/projects/tydoc/tydoc/got/test/response-parse.ts',
  '/Users/jasonkuhrt/projects/tydoc/tydoc/got/test/retry.ts',
  '/Users/jasonkuhrt/projects/tydoc/tydoc/got/test/stream.ts',
  '/Users/jasonkuhrt/projects/tydoc/tydoc/got/test/timeout.ts',
  '/Users/jasonkuhrt/projects/tydoc/tydoc/got/test/unix-socket.ts',
  '/Users/jasonkuhrt/projects/tydoc/tydoc/got/test/url-to-options.ts',
  '/Users/jasonkuhrt/projects/tydoc/tydoc/got/test/weakable-map.ts',
  '/Users/jasonkuhrt/projects/tydoc/tydoc/got/benchmark/index.ts',
  '/Users/jasonkuhrt/projects/tydoc/tydoc/got/benchmark/server.ts',
  '/Users/jasonkuhrt/projects/tydoc/tydoc/got/source/as-promise/create-rejection.ts',
  '/Users/jasonkuhrt/projects/tydoc/tydoc/got/source/as-promise/index.ts',
  '/Users/jasonkuhrt/projects/tydoc/tydoc/got/source/as-promise/normalize-arguments.ts',
  '/Users/jasonkuhrt/projects/tydoc/tydoc/got/source/as-promise/parse-body.ts',
  '/Users/jasonkuhrt/projects/tydoc/tydoc/got/source/as-promise/types.ts',
  '/Users/jasonkuhrt/projects/tydoc/tydoc/got/source/core/calculate-retry-delay.ts',
  '/Users/jasonkuhrt/projects/tydoc/tydoc/got/source/core/index.ts',
  '/Users/jasonkuhrt/projects/tydoc/tydoc/got/source/utils/deep-freeze.ts',
  '/Users/jasonkuhrt/projects/tydoc/tydoc/got/source/utils/deprecation-warning.ts',
  '/Users/jasonkuhrt/projects/tydoc/tydoc/got/test/helpers/create-http-test-server.ts',
  '/Users/jasonkuhrt/projects/tydoc/tydoc/got/test/helpers/create-https-test-server.ts',
  '/Users/jasonkuhrt/projects/tydoc/tydoc/got/test/helpers/slow-data-stream.ts',
  '/Users/jasonkuhrt/projects/tydoc/tydoc/got/test/helpers/types.ts',
  '/Users/jasonkuhrt/projects/tydoc/tydoc/got/test/helpers/with-server.ts',
  '/Users/jasonkuhrt/projects/tydoc/tydoc/got/source/core/utils/dns-ip-version.ts',
  '/Users/jasonkuhrt/projects/tydoc/tydoc/got/source/core/utils/get-body-size.ts',
  '/Users/jasonkuhrt/projects/tydoc/tydoc/got/source/core/utils/get-buffer.ts',
  '/Users/jasonkuhrt/projects/tydoc/tydoc/got/source/core/utils/is-form-data.ts',
  '/Users/jasonkuhrt/projects/tydoc/tydoc/got/source/core/utils/is-response-ok.ts',
  '/Users/jasonkuhrt/projects/tydoc/tydoc/got/source/core/utils/options-to-url.ts',
  '/Users/jasonkuhrt/projects/tydoc/tydoc/got/source/core/utils/proxy-events.ts',
  '/Users/jasonkuhrt/projects/tydoc/tydoc/got/source/core/utils/timed-out.ts',
  '/Users/jasonkuhrt/projects/tydoc/tydoc/got/source/core/utils/unhandle.ts',
  '/Users/jasonkuhrt/projects/tydoc/tydoc/got/source/core/utils/url-to-options.ts',
  '/Users/jasonkuhrt/projects/tydoc/tydoc/got/source/core/utils/weakable-map.ts',
  '/Users/jasonkuhrt/projects/tydoc/tydoc/got/test/types/create-test-server/index.d.ts',
  '/Users/jasonkuhrt/projects/tydoc/tydoc/got/test/types/slow-stream/index.d.ts'
] +0ms
  tydoc:extract entrypoints: ["/Users/jasonkuhrt/projects/tydoc/tydoc/got/source"] +1ms
  tydoc:extract:export start +0ms
  tydoc:extract:export -> node kind is VariableDeclaration +0ms
  tydoc:extract:export -> type text is "import(\"/Users/jasonkuhrt/projects/tydoc/tydoc/got/source/types\").Got" +6ms
  tydoc:extract:visible start +0ms
  tydoc:extract:visible -> type text is "import(\"/Users/jasonkuhrt/projects/tydoc/tydoc/got/source/types\").Got" +2ms
  tydoc:extract:visible -> type location is app +2ms
  tydoc:extract:visible -> type is indexable +1ms
  tydoc:extract:visible -> type is callable +3ms
  tydoc:doc provisioning entry in type index: (source/types).Got +0ms
  tydoc:extract:visible handle property: PropertySignature stream import("/Users/jasonkuhrt/projects/tydoc/tydoc/got/source/types").GotStream +10ms
  tydoc:extract:visible start +0ms
  tydoc:extract:visible -> type text is "import(\"/Users/jasonkuhrt/projects/tydoc/tydoc/got/source/types\").GotStream" +1ms
  tydoc:extract:visible -> type location is app +2ms
  tydoc:extract:visible -> type is indexable +1ms
  tydoc:extract:visible -> type is callable +1ms
  tydoc:doc provisioning entry in type index: (source/types).GotStream +13ms
  tydoc:extract:visible handle callable return: any +8ms
  tydoc:extract:visible start +0ms
  tydoc:extract:visible -> type text is "any" +0ms
  tydoc:extract:visible -> type location is typeScriptCore +0ms
  tydoc:extract:visible -> type is not indexable +0ms
  tydoc:extract:visible -> type is primitive +0ms
  tydoc:extract:visible handle callable param: Parameter url string | import("url").URL +2ms
  tydoc:extract:visible start +0ms
  tydoc:extract:visible -> type text is "string | import(\"url\").URL" +1ms
  tydoc:extract:visible -> type location is inline +2ms
  tydoc:extract:visible -> type is not indexable +1ms
  tydoc:extract:visible -> type is union +2ms
  tydoc:extract:visible -> handle union member string +3ms
  tydoc:extract:visible start +0ms
  tydoc:extract:visible -> type text is "string" +1ms
  tydoc:extract:visible -> type location is typeScriptCore +0ms
  tydoc:extract:visible -> type is not indexable +0ms
  tydoc:extract:visible -> type is primitive +0ms
  tydoc:extract:visible -> handle union member import("url").URL +0ms
  tydoc:extract:visible start +0ms
  tydoc:extract:visible -> type text is "import(\"url\").URL" +1ms
  tydoc:extract:visible -> type location is dep +2ms
  tydoc:extract:visible -> location is a dependency, stopping here +0ms
  tydoc:extract:visible handle callable param: Parameter options Merge<any, { isStream?: true; }> +2ms
  tydoc:extract:visible start +0ms
  tydoc:extract:visible -> type text is "Merge<any, { isStream?: true; }>" +1ms
  tydoc:extract:visible -> type location is app +1ms
  tydoc:extract:visible -> type is indexable +1ms
  tydoc:extract:visible -> type is intersection +0ms
  tydoc:doc provisioning entry in type index: (source/types).Merge +27ms
  tydoc:extract:visible -> handle intersection member Pick<any, string | number | symbol> +2ms
  tydoc:extract:visible start +0ms
  tydoc:extract:visible -> type text is "Pick<any, string | number | symbol>" +0ms
  tydoc:extract:visible -> type location is typeScriptStandardLibrary +0ms
  tydoc:extract:visible -> location is standard lib and not array, stopping here +0ms
  tydoc:extract:visible -> handle intersection member { isStream?: true; } +1ms
  tydoc:extract:visible start +0ms
  tydoc:extract:visible -> type text is "{ isStream?: true; }" +0ms
  tydoc:extract:visible -> type location is app +0ms
  tydoc:extract:visible -> type is not indexable +0ms
  tydoc:extract:visible -> type is object +0ms
  tydoc:extract:visible handle property: PropertySignature isStream true +0ms
  tydoc:extract:visible start +1ms
  tydoc:extract:visible -> type text is "true" +0ms
  tydoc:extract:visible -> type location is inline +0ms
  tydoc:extract:visible -> type is not indexable +0ms
  tydoc:extract:visible -> type is literal +0ms
  tydoc:extract -> type had alias Merge (extracting a doc node for it) +315ms
bin.js fromSource [filePath]

EPD from local package source

Positionals:
  filePath  Entrypoint path(s) into the package. The main module will always be
            considered an entrypoint so there is no need to manually specify it
            here.

Options:
      --version                    Show version number                 [boolean]
      --help                       Show help                           [boolean]
      --debug                      Enable deug logs. Convenience for setting
                                   DEBUG=tydoc* envar.[boolean] [default: false]
  -j, --json                       Output results as structured JSON data
                                                      [boolean] [default: false]
  -m, --markdown                                       [boolean] [default: true]
  -d, --dir                        Project path e.g.: ./projects/my-package
                                                                        [string]
      --sourceMainEntrypointPath   Absolute path to the source main entrypoint.
                                   By default a discovery attempt is made by
                                   running heuristics against a combination of
                                   package.json and tsconfig.json however it
                                   only covers common patterns, not all possible
                                   setups. If you give a relative path it is
                                   relative to the project directory (--dir).
                                                                        [string]
      --flatTermsSection           For use with markdown rendering. Whether or
                                   not the API terms section should have a title
                                   and nest its term entries under it. If false,
                                   term entry titles are de-nested by one level.
                                                      [boolean] [default: false]
      --ignoreDiagnostics          Should Tydoc ignore any TypeScript
                                   diagnostics that are raised? If not ignored
                                   then Tydoc will refuse to extract when
                                   diagnostics are raised.
                                                      [boolean] [default: false]
      --ignoreDiagnosticsMatching  JSON5 of one (or an array of) diagnostic
                                   filters. Examples:

                                   { path: '/foo/bar/.*' }
                                   { code: '2\d{2}5' }
                                   { category: 'error' }
                                   [{ path: '/foo/bar/.*', code '24.*' }]
                                                                        [string]

InvalidOperationError: Expected to find a symbol.
    at Object.throwIfNullOrUndefined (/Users/jasonkuhrt/projects/tydoc/tydoc/node_modules/@ts-morph/common/dist/ts-morph-common.js:423:19)
    at Type.getSymbolOrThrow (/Users/jasonkuhrt/projects/tydoc/tydoc/node_modules/ts-morph/dist/ts-morph.js:17122:30)
    at /Users/jasonkuhrt/projects/tydoc/tydoc/packages/extractor/source/extract.ts:495:23
    at Array.map (<anonymous>)
    at typeParametersDocsFromType (/Users/jasonkuhrt/projects/tydoc/tydoc/packages/extractor/source/extract.ts:494:17)
    at extractAliasIfOne (/Users/jasonkuhrt/projects/tydoc/tydoc/packages/extractor/source/extract.ts:586:21)
    at /Users/jasonkuhrt/projects/tydoc/tydoc/packages/extractor/source/extract.ts:471:7
    at Manager.indexTypeIfApplicable (/Users/jasonkuhrt/projects/tydoc/tydoc/packages/extractor/source/doc.ts:97:24)
    at fromType (/Users/jasonkuhrt/projects/tydoc/tydoc/packages/extractor/source/extract.ts:470:20)
    at /Users/jasonkuhrt/projects/tydoc/tydoc/packages/extractor/source/extract.ts:542:17
```
